version: '3.8'

services:
  web:
    image: 3-tire-front
    container_name: 3-tire-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
