name: Deploy Docker Compose App

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Print Docker Compose Version
        run: docker-compose --version

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Docker Compose App
        run: |
          cd /home/ubuntu/finch/finch-frontend
          git stash || true
          git fetch origin
          git checkout dev
          git pull origin dev
          cd ..
          docker-compose up -d --build
          docker image prune -f
          docker ps
