name: Deploy Docker Compose App

on:
  push:
    branches: [dev]  # Triggers on push to 'dev' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker
          sudo usermod -aG docker $USER

      - name: Build and Run Docker Compose App
        run: |
          # Ensure on dev branch
          git fetch origin
          git checkout dev
          git pull origin dev

          # Build and start containers
          docker-compose up -d --build

          # Clean up unused Docker images
          docker image prune -f

          # Show running containers
          docker ps
