name: Deploy Docker Compose App

on:
  push:
    branches: [dev]  # Triggers on push to 'dev' branch

jobs:
  deploy:
    runs-on: Finch-runner  

    steps:
      - name: Print Docker Compose Version
        run: |
          sudo docker-compose --version

      - name: Checkout Code and Deploy App
        run: |
          cd /home/ubuntu/finch/finch-frontend

          # Ensure you're on the dev branch
          git stash || true
          git fetch origin
          git checkout dev
          git pull origin dev

          # Go to project root (where docker-compose.yaml is located)
          cd ..

          # Build and start the app
          sudo docker-compose up -d --build

          # Clean up unused images
          sudo docker image prune -f

          # Show running containers
          sudo docker ps
